[package]
edition = '2021'
name = 'exonr'
version = '0.1.0'

[lib]
crate-type = ['staticlib']
name = 'exonr'

[dependencies]
arrow = { version = "50.0.0", features = ["ffi"] }
datafusion = "37"
exon = { version = "0.15", features = ["all"] }
extendr-api = "0.6"
tokio = { version = '1', features = ['rt'] }
url = "2.4.0"

[workspace]
