[package]
description = "Executable benchmarks for exon"
edition = "2021"
homepage = {workspace = true}
keywords = ["exon", "bioinformatics", "rust"]
license = {workspace = true}
name = "exon-benchmarks"
readme = "README.md"
version = "0.3.3-beta.3"

[dependencies]
clap = {version = "4.4.6", features = ["derive"]}
datafusion = {workspace = true}
exon = {path = "../exon", features = ["all"], version = "0.3.3-beta.3" }
noodles = {version = "0.52", features = ["core", "vcf", "bgzf"]}
tokio = {version = "1", features = ["full"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
