[package]
description = "Executable benchmarks for exon"
edition = "2021"
homepage = {workspace = true}
keywords = ["exon", "bioinformatics", "rust"]
license = {workspace = true}
name = "exon-benchmarks"
readme = "README.md"
version = "0.2.7-rc.2"

[dependencies]
clap = {version = "4.4.2", features = ["derive"]}
datafusion = {workspace = true}
exon = {path = "../exon", features = ["all"], version = "0.2.7-rc.4" }
noodles = {version = "0.50", features = ["core", "vcf", "bgzf"]}
tokio = {version = "1", features = ["full"]}
