[package]
description = "Exon SAM"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "exon-sam"
readme.workspace = true
repository.workspace = true
version = {workspace = true}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
